apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset01-app
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: "my-app"
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: my-app
        image: busybox
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: "/data"
          name: my-vol
  volumeClaimTemplates:
  - metadata:
      name: my-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi